import type { Card } from './types';

/**
 * Cards to sort. Scoped to metrics only — session/identity, agent configuration, per-engine
 * model/provider config, and event-stream entries have been pruned so the sort focuses on
 * the information architecture for usage and performance data.
 *
 * Keep this list ordered from "high-level / overview" to "low-level / per-provider" so that
 * the initial center column has a sensible starting order before the user touches anything.
 */
export const CARDS: Card[] = [
  // Top-line latency / turn metrics
  {
    id: 'avg-e2e-latency',
    label: 'Avg E2E latency',
    description:
      'Mean end-to-end response latency across the session: time from the user finishing speaking to the agent starting to speak back.',
  },
  {
    id: 'avg-llm-ttft',
    label: 'Avg LLM TTFT',
    description:
      'Time to first token from the LLM — how long after the prompt was sent until the first response token streamed back. Lower is faster perceived response.',
  },
  {
    id: 'avg-tts-ttfb',
    label: 'Avg TTS TTFB',
    description:
      'Time to first byte from TTS — how long after we asked the voice provider to speak until the first audio chunk arrived.',
  },
  {
    id: 'avg-transcription-delay',
    label: 'Avg transcription delay',
    description:
      'Lag between the user finishing a phrase and the STT producing the final transcript the LLM acts on.',
  },
  {
    id: 'avg-end-of-turn-delay',
    label: 'Avg end of turn delay',
    description:
      'How long after the user stops talking before the agent considers their turn over and starts responding.',
  },
  {
    id: 'avg-on-user-turn-completed-delay',
    label: 'Avg on_user_turn_completed delay',
    description:
      'Time spent inside the user-supplied on_user_turn_completed hook — custom logic that runs after every user turn (e.g. RAG lookups).',
  },

  // Interruption metrics
  {
    id: 'avg-detection-delay',
    label: 'Avg detection delay',
    description:
      'How long it took the agent to notice that the user had started speaking over it (barge-in). Lower means snappier interruption handling.',
  },
  {
    id: 'interruptions',
    label: 'Interruptions',
    description: 'Count of times the user successfully interrupted the agent mid-utterance.',
  },
  {
    id: 'backchannels',
    label: 'Backchannels',
    description:
      'Short user utterances (“mm-hmm”, “yeah”) that the agent recognized as acknowledgments rather than full interruptions.',
  },

  // Usage rollups
  {
    id: 'llm-input-output-tokens',
    label: 'LLM input / output tokens',
    description:
      'Total tokens sent to and received from the LLM across the whole session. Primary driver of LLM cost.',
  },
  {
    id: 'tts-characters',
    label: 'TTS characters',
    description:
      'Total characters synthesized by the TTS provider over the session. Most TTS pricing is per-character.',
  },
  {
    id: 'stt-duration',
    label: 'STT duration',
    description:
      'Total audio time submitted to STT. Most STT pricing is per-minute of audio processed.',
  },

  // LLM detail metrics
  {
    id: 'llm-input-tokens',
    label: 'Input tokens',
    context: 'LLM',
    description: 'Tokens sent to the LLM as prompt context, summed across all turns.',
  },
  {
    id: 'llm-input-text-tokens',
    label: 'Input text tokens',
    context: 'LLM',
    description:
      'Subset of input tokens that came from plain text (transcripts, system prompt, history).',
  },
  {
    id: 'llm-input-audio-tokens',
    label: 'Input audio tokens',
    context: 'LLM',
    description:
      'Subset of input tokens for raw audio frames sent to a speech-native LLM (e.g. Realtime API).',
  },
  {
    id: 'llm-input-image-tokens',
    label: 'Input image tokens',
    context: 'LLM',
    description: 'Subset of input tokens consumed by images attached to the prompt.',
  },
  {
    id: 'llm-input-cached-tokens',
    label: 'Input cached tokens',
    context: 'LLM',
    description:
      'Input tokens that were served from the provider’s prompt cache. Usually billed at a steep discount.',
  },
  {
    id: 'llm-input-cached-text-tokens',
    label: 'Input cached text tokens',
    context: 'LLM',
    description: 'Cached-input tokens that were specifically text.',
  },
  {
    id: 'llm-input-cached-audio-tokens',
    label: 'Input cached audio tokens',
    context: 'LLM',
    description: 'Cached-input tokens that were specifically audio.',
  },
  {
    id: 'llm-input-cached-image-tokens',
    label: 'Input cached image tokens',
    context: 'LLM',
    description: 'Cached-input tokens that were specifically images.',
  },
  {
    id: 'llm-output-tokens',
    label: 'Output tokens',
    context: 'LLM',
    description:
      'Tokens generated by the LLM across all turns. Drives output-side cost and response length.',
  },
  {
    id: 'llm-output-text-tokens',
    label: 'Output text tokens',
    context: 'LLM',
    description: 'Subset of output tokens that were text (the spoken response, transcribed).',
  },
  {
    id: 'llm-output-audio-tokens',
    label: 'Output audio tokens',
    context: 'LLM',
    description: 'Subset of output tokens for raw audio emitted by a speech-native LLM.',
  },
  {
    id: 'llm-session-duration',
    label: 'Session duration',
    context: 'LLM',
    description:
      'How long the LLM connection was held open this session. Relevant for Realtime / streaming APIs that bill on connection time.',
  },

  // TTS detail metrics
  {
    id: 'tts-audio-duration',
    label: 'Audio duration',
    context: 'TTS',
    description:
      'Total seconds of audio produced by TTS — roughly, how long the agent was talking.',
  },
  {
    id: 'tts-characters-count',
    label: 'Characters count',
    context: 'TTS',
    description: 'Total characters submitted to the TTS provider for synthesis.',
  },
  {
    id: 'tts-input-tokens',
    label: 'Input tokens',
    context: 'TTS',
    description: 'For token-billed TTS providers, tokens sent in (instead of characters).',
  },
  {
    id: 'tts-output-tokens',
    label: 'Output tokens',
    context: 'TTS',
    description: 'For token-billed TTS providers, tokens produced.',
  },

  // STT detail metrics
  {
    id: 'stt-audio-duration',
    label: 'Audio duration',
    context: 'STT',
    description: 'Total seconds of user audio transcribed.',
  },
  {
    id: 'stt-input-tokens',
    label: 'Input tokens',
    context: 'STT',
    description: 'For token-billed STT providers, tokens charged on the input side.',
  },
  {
    id: 'stt-output-tokens',
    label: 'Output tokens',
    context: 'STT',
    description: 'For token-billed STT providers, tokens charged on the output (transcript) side.',
  },

  // Interruption detail metrics
  {
    id: 'interruption-total-requests',
    label: 'Total requests',
    context: 'Interruption',
    description: 'How many times turn-detection was invoked across the session.',
  },
];

export const CARDS_BY_ID: Record<string, Card> = Object.fromEntries(CARDS.map((c) => [c.id, c]));
