import type { ReactNode, SyntheticEvent } from 'react';
import { cn } from '@/lib/utils';

interface SettingsRowProps {
  title: ReactNode;
  subtitle: ReactNode;
  avatar?: ReactNode;
  action?: ReactNode;
  className?: string;
  children?: ReactNode;
  onClick?: (e: SyntheticEvent) => void;
}

export const SettingsList = ({ children }: { children: ReactNode }) => (
  <div className="divide-separator1 border-separator1 w-full divide-y rounded border">
    {children}
  </div>
);

export const SettingsListItem = ({
  title,
  subtitle,
  children,
  avatar,
  action,
  className,
  onClick,
}: SettingsRowProps) => {
  return (
    <div
      className={cn(
        'flex w-full items-center justify-between gap-4 p-4',
        {
          'hover:bg-bg2 hover:cursor-pointer': !!onClick,
        },
        className,
      )}
      onClick={onClick}
    >
      <div className="flex items-center gap-4">
        {avatar}
        <div className="space-y-1 text-sm">
          <div className="text-fg0">{title || 'Autogenerated'}</div>
          <div className="text-fg3 text-xs">{subtitle}</div>
        </div>
      </div>
      {children}
      {action}
    </div>
  );
};
